# Generated by Django 4.2.21 on 2026-04-29 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='main_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('need', 'Need'), ('offer', 'Offer')], max_length=5)),
                ('category', models.CharField(choices=[('goods', 'Goods'), ('food', 'Food'), ('childcare', 'Childcare'), ('eldercare', 'Eldercare'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('legal', 'Legal'), ('medical', 'Medical'), ('mental_health', 'Mental Health'), ('education', 'Education'), ('labor', 'Labor'), ('technology', 'Technology'), ('financial', 'Financial'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=20)),
                ('kind', models.CharField(choices=[('good', 'Good'), ('service', 'Service')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='main_app.listing')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='main_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('goods', 'Goods'), ('food', 'Food'), ('childcare', 'Childcare'), ('eldercare', 'Eldercare'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('legal', 'Legal'), ('medical', 'Medical'), ('mental_health', 'Mental Health'), ('education', 'Education'), ('labor', 'Labor'), ('technology', 'Technology'), ('financial', 'Financial'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_interests', to='main_app.profile')),
            ],
            options={
                'unique_together': {('profile', 'category')},
            },
        ),
    ]
